networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "13306:3306"
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
    #command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "algafood-api.jar"]
    environment:
      #- ENVIRONMENT_URL=http://algafood-api:8080
      - DB_HOST=algafood-mysql
      - SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
      - SPRING_SESSION_STORE_TYPE=redis
      - SPRING_DATA_REDIS_HOST=algafood-redis
      - SPRING_PROFILES_ACTIVE=development-docker
      - OAUTH2_CLIENT_ID=$OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$OAUTH2_CLIENT_SECRET
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql
    deploy:
      replicas: 2

  algafood-redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    networks:
      - algafood-network

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api